name: PHP Composer

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Start Docker containers
      run: docker-compose up -d
      working-directory: ./docker-symfony

    - name: Validate composer.json and composer.lock
      run: docker-compose exec php composer validate
      working-directory: ./docker-symfony

    - name: Install dependencies
      run: docker-compose exec php composer install --prefer-dist --no-progress --no-suggest
      working-directory: ./docker-symfony
    
    - name: Test action
      run: docker-compose exec php bin/console -V
      working-directory: ./docker-symfony
