name: PHP Composer

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Start Docker containers
      run: (cd docker-symfony/ && docker-compose up -d)

    - name: Validate composer.json and composer.lock
      run: (cd docker-symfony/ && docker-compose exec php composer validate)

    - name: Install dependencies
      run: (cd docker-symfony/ && docker-compose exec php composer install --prefer-dist --no-progress --no-suggest)
    
    - name: Test action
      run: (cd docker-symfony/ && docker-compose exec php bin/console -V)
