name: Docker symfony CI run unit tests

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: docker-php-sf-build
    steps:
    - uses: actions/checkout@v1
    
    - name: Build docker containers
      working-directory: './docker'
      run: docker-compose up -d

    - name: Validate composer.json and composer.lock
      working-directory: './docker'
      run: docker-compose exec -T php composer validate

    - name: Install dependencies
      working-directory: './docker'
      run: docker-compose exec -T php composer install --prefer-dist --no-progress --no-suggest

    - name: Run unit tests
      working-directory: './docker'
      run: docker-compose exec -T php bin/phpunit
