name: Run tests

on:
  push:
    branches: 
      - master

jobs:      
  unit:
    runs-on: ubuntu-latest
    name: docker-php-sf-unit
    steps:
    - uses: actions/checkout@v1
    - name: Cache docker build
      id: cache
      uses: actions/cache@v1
      with:
        path: ./docker
        key: docker-build-test-key
    - name: Rebuild docker
      working-directory: './docker'
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        docker-compose up -d
        docker-compose exec -T php composer install --prefer-dist --no-progress --no-suggest
    - name: Run unit tests
      working-directory: './docker'
      if: steps.cache.outputs.cache-hit == 'true'
      run: docker-compose exec -T php bin/phpunit
